[build]
builder = "nixpacks"
buildCommand = "npx prisma db push && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
MOCK_EMAIL = "false"
EMAIL_FROM = "TechTrust <noreply@techtrust.app>"
