/**
 * US States & Cities — shared across all signup/register forms
 * Mirrors /techtrust-mobile/src/constants/us-states.ts
 */

export const US_STATES: Array<{ code: string; name: string }> = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'DC', name: 'District of Columbia' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
]

export const CITIES_BY_STATE: Record<string, string[]> = {
  FL: [
    'Aventura','Boca Raton','Boynton Beach','Bradenton','Cape Coral',
    'Clearwater','Coral Gables','Coral Springs','Davie','Daytona Beach',
    'Deerfield Beach','Doral','Fort Lauderdale','Fort Myers','Fort Pierce',
    'Gainesville','Hialeah','Hollywood','Homestead','Jacksonville',
    'Jupiter','Kissimmee','Lake Worth','Lakeland','Largo',
    'Margate','Melbourne','Miami','Miami Beach','Miami Gardens',
    'Miramar','Naples','North Miami','Ocala','Orlando',
    'Ormond Beach','Palm Bay','Palm Beach','Palm Beach Gardens','Palm Coast',
    'Pembroke Pines','Pensacola','Plantation','Pompano Beach','Port St. Lucie',
    'Sarasota','St. Petersburg','Sunrise','Tallahassee','Tampa',
    'West Palm Beach','Weston',
  ],
}

export const ACTIVE_STATES = ['FL']
