-- AlterTable: Add fee breakdown fields to payments
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "appServiceFee" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "serviceCommission" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "serviceCommissionPercent" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "partsFee" DECIMAL(10,2) NOT NULL DEFAULT 0;
