-- CreateEnum
CREATE TYPE "AppointmentStatus" AS ENUM ('REQUESTED', 'CONFIRMED', 'PROVIDER_EN_ROUTE', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW');

-- CreateEnum
CREATE TYPE "EstimateType" AS ENUM ('DIRECT', 'DIAGNOSTIC', 'COMPETING');

-- CreateEnum
CREATE TYPE "RepairInvoiceStatus" AS ENUM ('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'APPROVED', 'DISPUTED');

-- AlterEnum NotificationType
ALTER TYPE "NotificationType" ADD VALUE 'APPOINTMENT_SCHEDULED';
ALTER TYPE "NotificationType" ADD VALUE 'APPOINTMENT_CONFIRMED';
ALTER TYPE "NotificationType" ADD VALUE 'APPOINTMENT_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE 'ESTIMATE_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'ESTIMATE_SHARED';
ALTER TYPE "NotificationType" ADD VALUE 'COMPETING_ESTIMATE_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE 'REPAIR_INVOICE_GENERATED';

-- AlterEnum ServiceType
ALTER TYPE "ServiceType" ADD VALUE 'DIAGNOSTIC';
